### ISSUE TITLE
Facebook SDK version has to be set manually.

### ISSUE THREAD

**Issue by waquidvp** [waquidvp/project-chameleon#1]
To avoid the error in the Android build:
```
AAPT: Error retrieving parent for item: 

No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
```

The Facebook SDK version has to be manually changed to 4.22.1 in both the app's build.gradle and the react-native-fbsdk build.gradle file for the build to work.

Refer to this issue in the react-native-fbsdk repo:
https://github.com/facebook/react-native-fbsdk/pull/339

**Comment by waquidvp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Facebook SDK version issue](https://trello.com/c/3gyubjZT/12-facebook-sdk-version-issue)

**Comment by jslok** [comment]
Same issue here.

**Comment by waquidvp** [comment]
The current fix is:
The Facebook SDK version has to be manually changed to 4.22.1 in both the app's build.gradle and the react-native-fbsdk build.gradle file for the build to work.

There is no other fix to my understanding.

**Comment by jslok** [comment]
@waquidvp  if you need to update fb sdk I described how I solved it here https://github.com/facebook/react-native-fbsdk/pull/339

**Comment by waquidvp** [comment]
This was fixed by updating gradle to the latest version.

Currently fixed in https://github.com/waquidvp/project-chameleon/commit/d73043462e3135eb64002e19b740db7145796186
